rabbit:
  image: rabbitmq:3-management
  container_name: rabbitmq
  environment:
    - RABBIT_HOST=rabbit
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=mypass
  ports:
    - "5672:5672"  # debug
    - "15672:15672"  # management
  volumes:
    - rabbitmq_data:/var/lib/rabbitmq