postgres:
  container_name: postgress
  restart: always
  image: postgres:alpine
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
  volumes:
    - postgres_data:/var/lib/postgresql/data/